# Quiz
# Define Colors
primaryColor = "#000000"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"
borderRadiusCard = "20px"
