# Quiz
# Define Colors

colorPrimary = "#43449C"
colorSecondary = "#A0D7C4"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
colorWhite = "#FFFFFF"
colorWhiteOpacity = "rgba(255, 255, 255, 0.5)"
colorBlack = "#000000"

image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"
borderRadiusCard = "20px"
borderRadiusCardSmall = "8px"

# Emails
contactEmail = "anonym@dopracenakole.cz"

# External URLs
urlFacebook = "https://www.facebook.com/spolekautomat"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlTwitter = "https://twitter.com/spolekautomat"
urlYoutube = "https://www.youtube.com/@spolekautomat"
urlAppStore = "https://apps.apple.com/cz/app/do-pr%C3%A1ce-na-kole/id1564442780"
urlGooglePlay = "https://play.google.com/store/apps/details?id=cz.dopracenakole"
