# COLORS

colorPrimary = "#43449C"
colorPrimaryDark = "#110547"
colorPrimaryOpacity = 0.1
colorSecondary = "#A0D7C4"
colorGray = "#D4D4D4"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
colorWhite = "#FFFFFF"
colorBlack = "#000000"
colorRed = "#F15857"
colorCustomFormFieldValidationErr = "#A0D7C4"
colorSecondaryBackgroundOpacity = 0.4
colorWhiteBackgroundOpacity = 0.2
colorWhiteBorderOpacity = 0.5

# STYLING ATTRIBUTES

# container used for registration forms
containerFormWidth = "752px"

# container used for main layout
containerContentWidth = "1024px"

# manually selected height that shows reports without internal scrollbar on desktop
dataReportIframeHeight = "1500px"

borderRadiusButtonSmall = "8px"
borderRadiusCard = "16px"
borderRadiusCardSmall = "8px"
maxWidthBanner = "876px"

image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"

notifyMessagePosition = "top"
mobileBottomPanelVisibleItems = 3

indexPageVisibleOfferCount = 6

# CONTACT DETAILS

# Emails
contactEmail = "kontakt@dopracenakole.cz"

# LOCAL URLS

urlRTWBBLogo = "#/"
urlLoginRegisterBackgroundImage = "/image/login-register-layout.webp"
urlBaseBackend = "https://test.dopracenakole.cz/"

# EXTERNAL URLS

urlAppStore = "https://apps.apple.com/cz/app/do-pr%C3%A1ce-na-kole/id1564442780"
urlAutoMat = "https://auto-mat.cz"
urlBlog = "https://dopracenakole.cz/novinky-do-prace-na-kole"
urlContact = "https://dopracenakole.cz/kontakt-do-prace-na-kole"
urlDonate = "https://auto-mat.cz/daruj-dopracenakole"
urlProjectSourceCode = "https://github.com/auto-mat/ride-to-work-by-bike-frontend"
urlFacebook = "https://www.facebook.com/spolekautomat"
urlFacebookRideToWorkByBike = "https://www.facebook.com/dopracenakole"
urlFaq = "https://www.dopracenakole.cz/o-vyzve/faq"
urlFreeSoftwareDefinition = "https://www.gnu.org/philosophy/free-sw.en.html"
urlGooglePlay = "https://play.google.com/store/apps/details?id=cz.dopracenakole"
urlHelpdesk = "https://dopracenakole.cz/kontakt-do-prace-na-kole"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlAppDataPrivacyPolicy = "https://auto-mat.cz/zasady"
urlAppDataTermsOfService = "https://dopracenakole.cz/obchodni-podminky"
urlRideToWorkByBike = "https://dopracenakole.cz"
urlRideToWorkByBikeOldFrontendDjangoApp = "https://dpnk.dopracenakole.fun"
urlRideToWorkByBikeOldFrontendDjangoAppAdmin = "admin/"
urlStravaPrivacyZones = "https://support.strava.com/hc/en-us/articles/115000173384-Privacy-Zones"
urlTwitter = "https://twitter.com/spolekautomat"
urlVideoLoggingRoutes = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlVideoOnboarding = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlYoutube = "https://www.youtube.com/@spolekautomat"
urlSizeConversionChart = "https://dopracenakole.cz/o-vyzve/trika#velikostni_tabulky"

# CHALLENGE DETAILS

challengeMonth = "may"
challengeStartDate = "2024-08-01T12:00:00"
challengeLoggingWindowDays = 8
defaultDistanceZero = "0.00"

# Challenge registration
entryFeePaymentMax = "2000"
entryFeePaymentOptions = "850,1500"
rtwbbChallengeEntryFeeOrderedProductName = "RTWBB challenge entry fee"
rtwbbDonationOrderedProductName = "RTWBB donation"
checkRegisterChallengeStatusIntervalSeconds = 20
checkRegisterChallengeStatusMaxRepetitions = 5
tripMaxFileUploadSizeMegabytes = 1


# Merchandise
iDontWantMerchandiseItemCode = "nic"


# API CONFIGURATION

apiBase = "https://test.dopracenakole.cz/rest/"
apiBaseRtwbbFeed = "https://dopracenakole.cz/feed/"
apiBaseIpAddress = "https://ipapi.co/json/"

apiDefaultVersion = "v1"
apiVersion2 = "v2"
apiDefaultLang = "cs"

urlApiCities = "cities/"
urlApiCommuteMode = "commute_mode/"
urlApiConfirmEmail = "auth/registration/verify-email/"
urlApiDiscountCoupon = "discount-coupon/"
urlApiHasOrganizationAdmin = "has-organization-admin/"
urlApiHasUserVerifiedEmail = "auth/registration/has-user-verified-email-address/"
urlApiIsUserOrganizationAdmin = "is-user-organization-admin/"
urlApiLogin = "auth/login/"
urlApiLoginGoogle = "auth/google/login/"
urlApiOrganizations = "organizations/"
urlApiLoginFacebook = "auth/facebook/login/"
urlApiMerchandise = "merchandise/"
urlApiMyOrganizationAdmin = "my-organization-admin/"
urlApiMyTeam = "my_team/"
urlApiOpenAppWithRestToken = "open-app-with-rest-token/"
urlApiOrganizationAdminOrganizationStructure = "organization-coordinator-organization-structure/"
urlApiPayuCreateOrder = "payu-create-order/"
urlApiRefresh = "auth/token/refresh/"
urlApiRegister = "auth/registration/"
urlApiRegisterChallenge = "register-challenge/"
urlApiRegisterCoordinator = "register-coordinator/"
urlApiResetPassword = "auth/password/reset/"
urlApiResetPasswordConfirm = "auth/password/reset/confirm/"
urlApiResultsByChallenge = "datareport-results-by-challenge/"
urlApiResults = "datareport-results/"
urlApiSendRegistrationConfirmationEmail = "auth/registration/send-confirmation-email/"
urlApiSendTeamMembershipInvitationEmail = "send-team-membership-invitation-email/"
urlApiStravaAuthAccount = "strava-auth/"
urlApiStravaConnectAccount = "strava-connect/"
urlApiStravaDisconnectAccount = "strava-disconnect/"
urlApiStravaGetAccount = "strava_account/"
urlApiStravaGetAccountSync = "strava_account/sync/"
urlApiSubsidiaries = "subsidiaries/"
urlApiTeams = "teams/"
urlApiTrips = "trips/"
urlApiChallengeRegistrationUser = "challenge/registration/user/"
urlApiThisCampaign = "this_campaign/"

checkIsEmailVerifiedInterval = 20 # seconds
checkIsThisCampaignCompetitionPhaseTypeInterval = 20 # seconds
feedRefreshCachedPostsIntervalHours = 24
apiFeedMaxOffersNumber = 50
apiFeedMaxPrizesNumber = 50
apiTripsSourceApplicationId = 'RTWBB web app'
apiTripsThirdPartyAppIdCyclers = "1"
apiTripsThirdPartyAppIdNaKolePrahou = "3"

# DATE TIME FORMATS

dateTimeFormatsAllLocales = '''
{
  "numeric": {
    "year": "numeric",
    "month": "numeric",
    "day": "numeric"
  },
  "monthYear": {
    "year": "numeric",
    "month": "long"
  },
  "monthDay": {
    "month": "numeric",
    "day": "numeric"
  },
  "monthDayHourMinute" : {
    "month": "numeric",
    "day": "numeric",
    "hour": "numeric",
    "minute": "numeric"
  },
  "weekday": {
    "weekday": "long"
  },
  "monthLongStringDay": {
    "day": "numeric",
    "month": "long"
  }
}
'''

# NUMBER FORMATS

numberFormatsAllLocales = '''
{
  "routeDistanceDecimalNumber": {
    "style": "decimal",
    "minimumFractionDigits": 2,
    "maximumFractionDigits": 2,
    "roundingMode": "floor"
  }
}
'''

# SECRETS

secretString = "SECRET"
googleLoginAppId = "SECRET"
facebookLoginAppId = "SECRET"
apiBaseRtwbbFeedBearerToken = "SECRET"

# LIBRARIES

facebookLoginSdkVersion = "v21.0"
facebookLoginSdkOptions = '''
{
  "scope": "email,public_profile"
}
'''

# MAP SETTINGS

mapProjection = "EPSG:3857"
mapCenterLon = "14.4378"
mapCenterLat = "50.0755"
mapZoom = "14"
mapGeocodingApiUrl = "https://nominatim.openstreetmap.org/reverse"
mapSourceRtwbb = "https://mnk-osm-tiles.dopracenakole.net/{z}/{x}/{y}.png"
mapSourceOsm = "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
