const citySlugMapping: Record<number, string> = {
  41: 'brandys-nad-labem',
  29: 'breclav',
  5: 'brno',
  14: 'ceske-budejovice',
  15: 'hradec-kralove',
  26: 'hranice',
  16: 'jablonec-nad-nisou',
  7: 'jihlava',
  17: 'jindrichuv-hradec',
  22: 'karvina',
  34: 'kladno',
  42: 'krnov',
  6: 'liberec',
  44: 'litvinov',
  40: 'most',
  27: 'nove-mesto-nad-metuji',
  24: 'novy-jicin',
  8: 'olomouc',
  9: 'ostrava',
  18: 'otrokovice',
  21: 'pardubice',
  10: 'plzen',
  4: 'praha',
  20: 'prerov',
  37: 'pribram',
  31: 'ricany-u-prahy',
  33: 'rychnov-nad-kneznou',
  36: 'trebic',
  11: 'uherske-hradiste',
  12: 'usti-nad-labem',
  35: 'zdar-nad-sazavou',
  32: 'zlin',
  30: 'znojmo',
};

export const getCitySlugFromId = (id: number): string => {
  return citySlugMapping[id] || '';
};
